apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-managment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: ride-managment
    spec:
      containers:
      - name: ride-managment
        image: strixman/ride-managment-microservice:latest
        ports:
        - containerPort: 80
        env:
        - name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: sdu
              key: sqlalchemy_database_uri
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jsk
              key: jwt_secret_key
        - name: LOGIT_IO_HOST
          valueFrom:
            secretKeyRef:
              name: lih
              key: logit_io_host
        - name: LOGIT_IO_PORT
          valueFrom:
            secretKeyRef:
              name: lip
              key: logit_io_port
        - name: GOOGLE_DIRECTIONS_API_KEY
          valueFrom:
            secretKeyRef:
              name: gdak
              key: google_directions_api_key
        livenessProbe:
          httpGet:
            port: 80
            path: /livez
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            port: 80
            path: /readyz
          initialDelaySeconds: 90
          periodSeconds: 60
          timeoutSeconds: 5
  selector:
    matchLabels:
      app: ride-managment
---
apiVersion: v1
kind: Service
metadata:
  name: ride-managment
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector: 
    app: ride-managment